version: '3.4'

networks:
  manageusersapi-dev:
    driver: bridge 

services:
  manageusersapi:
    image: manageusersapi:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=userdb;username=apiuser;password=apiuser"
    networks:
      - manageusersapi-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "apiuser"
      POSTGRES_PASSWORD: "apiuser"
      POSTGRES_DB: "userdb"
    networks:
      - manageusersapi-dev
volumes:
  db_volume: